---
- name: Ensure python3-requests is installed
  ansible.builtin.yum:
    name: python3-requests
    state: present

- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ proxy_group }}"
    gid: 13
    state: present
    system: true

- name: Ensure groups exists
  ansible.builtin.group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
    state: present
    system: true
  loop:
    - group: shadow
      gid: 42
    - group: utmp
      gid: 43
    - group: crontab
      gid: 101
    - group: ssl-cert
      gid: 102

- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
    uid: 13
    create_home: true
    home: "{{ proxy_home }}"
    shell: /usr/sbin/nologin
    state: present
    system: true

- name: Ensure cache dirs exist
  ansible.builtin.file:
    path: "{{ proxy_cache }}/{{ item }}"
    state: directory
    owner: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
    mode: '0755'
  loop:
    - '00'
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    - '07'
    - '08'
    - '09'
    - '0A'
    - '0B'
    - '0C'
    - '0D'
    - '0E'
    - '0F'

- name: Ensure log dir exists
  ansible.builtin.file:
    path: "{{ proxy_log }}"
    state: directory
    owner: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
    mode: '0755'

- name: Deploy squid.conf
  ansible.builtin.template:
    src: squid.conf.j2
    dest: "{{ proxy_home }}/squid.conf"
    owner: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
    mode: '0644'

- name: Install squid container
  community.docker.docker_container:
      name: "squid"
      image: "ubuntu/squid"
      env:
        TZ: "UTC"
      state: started
      restart_policy: "always"
      recreate: true # to make sure it's in it's latest state given it's checks
      ports:
      - "0.0.0.0:3128:3128"
      volumes:
        - "{{ proxy_home }}/squid.conf:/etc/squid/squid.conf:z"
        - "{{ proxy_log }}:/var/log/squid:Z"
        - "{{ proxy_cache }}:/var/spool/squid:Z"

- name: Wait for port
  ansible.builtin.wait_for:
    port: "{{ proxy_port }}"
    delay: 10
